# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/feed_icons')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
